"""add language to posts

Revision ID: 848f87967798
Revises: 6310f0345c88
Create Date: 2025-03-31 10:25:06.514479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848f87967798'
down_revision = '6310f0345c88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
